### ISSUE TITLE
& char in a comment causes install prompt from sqlplus

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelCommons#2]
ExcelCommons/plsql/ExcelTypes.pkb line 26 and 106 contains an '&' char which causes sqlplus and other tools to prompt for input.

 -- BEGIN CSS parser constants & structures

-- END CSS parser constants & structures

Need to either set define off or change to the word 'and'.

Workaround is to simply press return both times when prompted.

**Comment by mbleron** [comment]
Fixed it in install scripts with SET DEFINE OFF.
https://github.com/mbleron/ExcelGen/commit/72dfc1177ede5d9ba494e324ae9c8d27acd4f702
